/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package linkBudget;

import java.awt.Font;
import java.text.DecimalFormat;
/**
 *
 * @author Vernon Shaw
 */
public class linkBudgetCalc extends javax.swing.JFrame {

    /**
     * Creates new form linkBudgetCalc
     */
    
    private static DecimalFormat df2 = new DecimalFormat(".##");
    public linkBudgetCalc() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        mfButtonGroup = new javax.swing.ButtonGroup();
        linkBudgetPanel = new javax.swing.JPanel();
        distanceInputLbl = new javax.swing.JLabel();
        unitsSelectLbl = new javax.swing.JLabel();
        mButton = new javax.swing.JRadioButton();
        fButton = new javax.swing.JRadioButton();
        distanceInputTxt = new javax.swing.JTextField();
        freqSelectLbl = new javax.swing.JLabel();
        freqInputTxt = new javax.swing.JTextField();
        MHzLbl = new javax.swing.JLabel();
        freeSpaceLossResultLbl = new javax.swing.JLabel();
        freeSpaceLossResultTxt = new javax.swing.JTextField();
        jKm = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        PowerTX = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextTxPowerW = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextTxPowerdB = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextTxGain = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextRxGain = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextTxLoss = new javax.swing.JTextField();
        jTextRxLoss = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        BCalculate = new javax.swing.JButton();
        jTextRxPower = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Link Budget Calculator");

        linkBudgetPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Free Space Loss Calculator"));

        distanceInputLbl.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        distanceInputLbl.setText("Please input distance:");

        unitsSelectLbl.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        unitsSelectLbl.setText("Please Choose Units of Length:");

        mfButtonGroup.add(mButton);
        mButton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        mButton.setText("Meters");
        mButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mButtonActionPerformed(evt);
            }
        });

        mfButtonGroup.add(fButton);
        fButton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        fButton.setText("Feet");
        fButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fButtonActionPerformed(evt);
            }
        });

        distanceInputTxt.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        freqSelectLbl.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        freqSelectLbl.setText("Please Input Frequency:");

        freqInputTxt.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        MHzLbl.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        MHzLbl.setText("MHz");

        freeSpaceLossResultLbl.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        freeSpaceLossResultLbl.setText("Free Space Loss    = ");

        freeSpaceLossResultTxt.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jKm.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jKm.setText("m");
        jKm.setToolTipText("");

        javax.swing.GroupLayout linkBudgetPanelLayout = new javax.swing.GroupLayout(linkBudgetPanel);
        linkBudgetPanel.setLayout(linkBudgetPanelLayout);
        linkBudgetPanelLayout.setHorizontalGroup(
            linkBudgetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(linkBudgetPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(linkBudgetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(linkBudgetPanelLayout.createSequentialGroup()
                        .addComponent(freeSpaceLossResultLbl)
                        .addGap(18, 18, 18)
                        .addComponent(freeSpaceLossResultTxt))
                    .addGroup(linkBudgetPanelLayout.createSequentialGroup()
                        .addGroup(linkBudgetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(distanceInputLbl)
                            .addComponent(unitsSelectLbl)
                            .addComponent(freqSelectLbl))
                        .addGap(18, 18, 18)
                        .addGroup(linkBudgetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(linkBudgetPanelLayout.createSequentialGroup()
                                .addComponent(mButton)
                                .addGap(18, 18, 18)
                                .addComponent(fButton))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, linkBudgetPanelLayout.createSequentialGroup()
                                .addGroup(linkBudgetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(distanceInputTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                                    .addComponent(freqInputTxt))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(linkBudgetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(MHzLbl)
                                    .addComponent(jKm))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        linkBudgetPanelLayout.setVerticalGroup(
            linkBudgetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(linkBudgetPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(linkBudgetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(freqSelectLbl)
                    .addComponent(freqInputTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MHzLbl))
                .addGap(18, 18, 18)
                .addGroup(linkBudgetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(distanceInputLbl)
                    .addComponent(distanceInputTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jKm))
                .addGap(21, 21, 21)
                .addGroup(linkBudgetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unitsSelectLbl)
                    .addComponent(mButton)
                    .addComponent(fButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(linkBudgetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(freeSpaceLossResultLbl)
                    .addComponent(freeSpaceLossResultTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Power Link Budget"));

        PowerTX.setText("Power (Tx)");

        jLabel3.setText("Gain (Tx)");

        jLabel4.setText("Gain (Rx)");

        jLabel5.setText("Loss (Tx)");

        jLabel6.setText("Loss (Rx)");

        jLabel2.setText("Watt");

        jTextTxPowerdB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTxPowerdBActionPerformed(evt);
            }
        });

        jLabel7.setText("dBm");

        jLabel8.setText("dBi");

        jLabel9.setText("dBi");

        jLabel10.setText("dB");

        jLabel11.setText("dB");

        BCalculate.setText("Calculate");
        BCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCalculateActionPerformed(evt);
            }
        });

        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PowerTX)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextTxPowerW)
                    .addComponent(jTextTxGain)
                    .addComponent(jTextRxGain)
                    .addComponent(jTextTxLoss)
                    .addComponent(jTextRxLoss, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel10))
                                .addGap(18, 18, 18)
                                .addComponent(jTextTxPowerdB, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7)))
                        .addGap(0, 188, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextRxPower, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PowerTX)
                    .addComponent(jTextTxPowerW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextTxPowerdB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextTxGain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextRxGain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextTxLoss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextRxLoss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(BCalculate)
                    .addComponent(jTextRxPower, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(linkBudgetPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(linkBudgetPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mButtonActionPerformed
        // TODO add your handling code here:
        double mF = Double.parseDouble(freqInputTxt.getText());
        double mM = Double.parseDouble(distanceInputTxt.getText());
        double LFS = -27.55 + 20*(Math.log(mF)) + 20*(Math.log(mM)) ;
        freeSpaceLossResultTxt.setText(String.valueOf(LFS));
        
    }//GEN-LAST:event_mButtonActionPerformed

    private void fButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fButtonActionPerformed
        // TODO add your handling code here:
        double fF = Double.parseDouble(freqInputTxt.getText());
        double fM = (Double.parseDouble(distanceInputTxt.getText())) * (0.30483);
        double LFS = -27.55 + 20*(Math.log(fF)) + 20*(Math.log(fM)) ;
        String sLFS = String.valueOf(LFS);
        freeSpaceLossResultTxt.setText(sLFS);
    }//GEN-LAST:event_fButtonActionPerformed

    private void BCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCalculateActionPerformed
        float TxPower,RxPower, TxLoss, RxLoss, FSL,TxGain,RxGain, LFS;
        //Initializing variables
        TxPower = Float.parseFloat(jTextTxPowerW.getText()) ;
        RxPower = Float.parseFloat(jTextTxPowerdB.getText());
        TxGain = Float.parseFloat(jTextTxGain.getText());
        RxGain= Float.parseFloat(jTextRxGain.getText());
        TxLoss= Float.parseFloat(jTextTxLoss.getText());
        RxLoss = Float.parseFloat(jTextRxLoss.getText());
        //Need to make LFS global
        LFS = Float.parseFloat(freeSpaceLossResultTxt.getText());
        RxPower = TxPower + TxGain + RxGain - Math.abs(TxLoss) - Math.abs(RxLoss) - Math.abs(LFS) ;
        
        jTextRxPower.setText(Float.toString(RxPower));
        Font newFont = new Font (jTextRxPower.getFont().getName(),Font.BOLD,jTextRxPower.getFont().getSize());
        jTextRxPower.setFont(newFont);
    }//GEN-LAST:event_BCalculateActionPerformed

    private void jTextTxPowerdBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTxPowerdBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTxPowerdBActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(linkBudgetCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(linkBudgetCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(linkBudgetCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(linkBudgetCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new linkBudgetCalc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BCalculate;
    private javax.swing.JLabel MHzLbl;
    private javax.swing.JLabel PowerTX;
    private javax.swing.JLabel distanceInputLbl;
    private javax.swing.JTextField distanceInputTxt;
    private javax.swing.JRadioButton fButton;
    private javax.swing.JLabel freeSpaceLossResultLbl;
    private javax.swing.JTextField freeSpaceLossResultTxt;
    private javax.swing.JTextField freqInputTxt;
    private javax.swing.JLabel freqSelectLbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jKm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextRxGain;
    private javax.swing.JTextField jTextRxLoss;
    private javax.swing.JTextField jTextRxPower;
    private javax.swing.JTextField jTextTxGain;
    private javax.swing.JTextField jTextTxLoss;
    private javax.swing.JTextField jTextTxPowerW;
    private javax.swing.JTextField jTextTxPowerdB;
    private javax.swing.JPanel linkBudgetPanel;
    private javax.swing.JRadioButton mButton;
    private javax.swing.ButtonGroup mfButtonGroup;
    private javax.swing.JLabel unitsSelectLbl;
    // End of variables declaration//GEN-END:variables
}
